INSERT INTO plants (common_name, latin_name, description, sun, water, soil, height_min, height_max, width_min, width_max, bloom_months, season_of_interest, plant_type, image_url) VALUES
('California Lilac', 'Ceanothus ''Ray Hartman''', 'Fast-growing large shrub or small tree with clusters of vivid blue flowers. Excellent for slopes and erosion control. Drought tolerant once established.', 'full sun', 'low', 'Well-drained', 8, 20, 8, 20, ARRAY['March', 'April', 'May'], ARRAY['Spring'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Ceanothus_Ray_Hartman.jpg/640px-Ceanothus_Ray_Hartman.jpg'),

('Salvia', 'Salvia leucantha', 'Mexican bush sage with velvety purple and white flower spikes that attract hummingbirds and butterflies. Long bloom season from summer through fall.', 'full sun', 'low', 'Well-drained', 3, 5, 3, 5, ARRAY['August', 'September', 'October', 'November'], ARRAY['Fall', 'Summer'], 'perennial', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Salvia_leucantha_2.jpg/640px-Salvia_leucantha_2.jpg'),

('Rockrose', 'Cistus purpureus', 'Mediterranean shrub with showy magenta flowers with dark spots. Very drought tolerant once established. Excellent for dry slopes.', 'full sun', 'low', 'Sandy, well-drained', 3, 4, 4, 5, ARRAY['April', 'May', 'June'], ARRAY['Spring', 'Summer'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cistus_purpureus_2.jpg/640px-Cistus_purpureus_2.jpg'),

('Blue Oat Grass', 'Helictotrichon sempervirens', 'Striking blue-gray ornamental grass forming a dense clump. Holds color year-round. Great textural accent in mixed plantings.', 'full sun', 'low', 'Well-drained', 2, 3, 2, 3, ARRAY['June', 'July'], ARRAY['Spring', 'Summer', 'Fall', 'Winter'], 'grass', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Helictotrichon_sempervirens_2.jpg/640px-Helictotrichon_sempervirens_2.jpg'),

('Pride of Madeira', 'Echium candicans', 'Bold architectural plant with towering blue-purple flower spikes. Spectacular when in bloom. Excellent for coastal and Mediterranean gardens.', 'full sun', 'low', 'Sandy, well-drained', 4, 6, 6, 8, ARRAY['March', 'April', 'May', 'June'], ARRAY['Spring'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Echium_candicans_Madeira.jpg/640px-Echium_candicans_Madeira.jpg'),

('Japanese Maple', 'Acer palmatum', 'Elegant small tree with delicate, deeply cut leaves. Outstanding fall color in shades of red, orange and gold. Many cultivars available.', 'part shade', 'moderate', 'Moist, well-drained', 10, 25, 10, 25, ARRAY['April'], ARRAY['Spring', 'Fall'], 'tree', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Acer_palmatum_001.jpg/640px-Acer_palmatum_001.jpg'),

('Lavender', 'Lavandula angustifolia', 'Classic Mediterranean herb-shrub with fragrant silver-gray foliage and spikes of purple flowers. Beloved by bees and butterflies. Extremely drought tolerant.', 'full sun', 'low', 'Sandy, alkaline', 1, 3, 2, 4, ARRAY['June', 'July', 'August'], ARRAY['Summer'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Lavandula_angustifolia_-_Lavendel.jpg/640px-Lavandula_angustifolia_-_Lavendel.jpg'),

('Coast Rosemary', 'Westringia fruticosa', 'Dense Australian shrub with soft gray-green foliage and small white flowers nearly year-round. Excellent substitute for rosemary in mild climates.', 'full sun', 'low', 'Well-drained', 3, 6, 4, 6, ARRAY['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'], ARRAY['Spring', 'Summer', 'Fall', 'Winter'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Westringia_fruticosa.jpg/640px-Westringia_fruticosa.jpg'),

('Fescue', 'Festuca glauca', 'Low-growing ornamental grass with fine blue-gray blades. Excellent for edging paths or mass planting. Very drought tolerant.', 'full sun', 'low', 'Well-drained', 1, 1, 1, 1, ARRAY['May', 'June'], ARRAY['Spring', 'Summer', 'Fall', 'Winter'], 'grass', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Festuca_glauca_-_blue_fescue.jpg/640px-Festuca_glauca_-_blue_fescue.jpg'),

('Toyon', 'Heteromeles arbutifolia', 'California native large shrub or small tree with clusters of bright red berries in winter. White flowers in summer attract pollinators. The plant that gave Hollywood its name.', 'full sun', 'low', 'Well-drained', 8, 15, 8, 12, ARRAY['June', 'July'], ARRAY['Winter', 'Summer'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Heteromeles_arbutifolia_2.jpg/640px-Heteromeles_arbutifolia_2.jpg'),

('Agapanthus', 'Agapanthus africanus', 'Reliable perennial with strap-like leaves and globe-shaped clusters of blue or white flowers on tall stalks. Excellent for borders and containers.', 'full sun', 'moderate', 'Well-drained', 2, 3, 2, 3, ARRAY['June', 'July', 'August'], ARRAY['Summer'], 'perennial', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Agapanthus_africanus_2.jpg/640px-Agapanthus_africanus_2.jpg'),

('Pineapple Guava', 'Acca sellowiana', 'Attractive evergreen shrub with silvery-green leaves and showy red and white flowers. Edible fruit in fall. Extremely tough and drought tolerant.', 'full sun', 'low', 'Well-drained', 10, 15, 10, 15, ARRAY['May', 'June'], ARRAY['Spring', 'Fall'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Feijoa_sellowiana_fruit.jpg/640px-Feijoa_sellowiana_fruit.jpg'),

('Butterfly Bush', 'Buddleja davidii', 'Fast-growing shrub with long arching panicles of fragrant flowers in purple, pink, or white. A magnet for butterflies and hummingbirds. Blooms summer through fall.', 'full sun', 'moderate', 'Well-drained', 5, 10, 5, 8, ARRAY['July', 'August', 'September', 'October'], ARRAY['Summer', 'Fall'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Buddleja_davidii_2.jpg/640px-Buddleja_davidii_2.jpg'),

('New Zealand Flax', 'Phormium tenax', 'Bold, architectural perennial with large sword-like leaves in green, bronze, red or striped. Provides strong vertical accent year-round. Drought tolerant once established.', 'full sun', 'low', 'Well-drained', 4, 6, 4, 6, ARRAY['June', 'July', 'August'], ARRAY['Spring', 'Summer', 'Fall', 'Winter'], 'perennial', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Phormium_tenax_2.jpg/640px-Phormium_tenax_2.jpg'),

('Manzanita', 'Arctostaphylos ''Dr. Hurd''', 'California native large shrub with beautiful mahogany-red bark, small white urn-shaped flowers, and red berries. Excellent wildlife plant. Very drought tolerant.', 'full sun', 'low', 'Well-drained, sandy', 8, 12, 8, 12, ARRAY['January', 'February', 'March'], ARRAY['Winter', 'Spring'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Arctostaphylos_manzanita.jpg/640px-Arctostaphylos_manzanita.jpg'),

('Penstemon', 'Penstemon heterophyllus', 'California native perennial with brilliant blue-purple tubular flowers beloved by hummingbirds. Blooms late spring through summer. Excellent for dry gardens.', 'full sun', 'low', 'Sandy, well-drained', 1, 2, 1, 2, ARRAY['May', 'June', 'July', 'August'], ARRAY['Spring', 'Summer'], 'perennial', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Penstemon_heterophyllus.jpg/640px-Penstemon_heterophyllus.jpg'),

('Flowering Maple', 'Abutilon hybridum', 'Fast-growing shrub with maple-like leaves and pendulous bell-shaped flowers in red, orange, yellow or pink. Blooms nearly year-round in mild climates.', 'part shade', 'moderate', 'Rich, moist', 4, 8, 4, 6, ARRAY['March', 'April', 'May', 'June', 'July', 'August', 'September', 'October'], ARRAY['Spring', 'Summer', 'Fall'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Abutilon_x_hybridum_2.jpg/640px-Abutilon_x_hybridum_2.jpg'),

('Heavenly Bamboo', 'Nandina domestica', 'Elegant shrub with fine-textured foliage that turns red in fall and winter. White flower clusters followed by persistent red berries. Nearly evergreen.', 'part shade', 'moderate', 'Moist, well-drained', 4, 8, 2, 4, ARRAY['June', 'July'], ARRAY['Fall', 'Winter'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Nandina_domestica_2.jpg/640px-Nandina_domestica_2.jpg'),

('Yarrow', 'Achillea millefolium', 'Tough, spreading perennial with ferny aromatic foliage and flat-topped clusters of flowers in white, yellow, pink or red. Excellent for dry, sunny borders. Long bloom season.', 'full sun', 'low', 'Well-drained, poor', 1, 3, 1, 3, ARRAY['May', 'June', 'July', 'August', 'September'], ARRAY['Spring', 'Summer', 'Fall'], 'perennial', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/AchilleaMillefolium.jpg/640px-AchilleaMillefolium.jpg'),

('Lemon Bottlebrush', 'Callistemon citrinus', 'Australian shrub with bright red bottlebrush-shaped flowers year-round in mild climates. Aromatic lemon-scented leaves when crushed. Excellent for hedges or specimens.', 'full sun', 'low', 'Well-drained', 6, 15, 6, 12, ARRAY['April', 'May', 'June', 'July', 'August', 'September'], ARRAY['Spring', 'Summer', 'Fall'], 'shrub', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Callistemon_citrinus_2.jpg/640px-Callistemon_citrinus_2.jpg');
